// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBEUDrXtVb0jrGzrNPZ7va7f97bPj2fwbo',
    appId: '1:919506372649:web:ee28f016866aa70c6a3438',
    messagingSenderId: '919506372649',
    projectId: 'flungry',
    authDomain: 'flungry.firebaseapp.com',
    storageBucket: 'flungry.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDc3-MlNdq_NfpoBGITlM4qnup7TVGTfvg',
    appId: '1:919506372649:android:e8458b4392bae9366a3438',
    messagingSenderId: '919506372649',
    projectId: 'flungry',
    storageBucket: 'flungry.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBqJ7Aan72yxl_iH8xwi6wN4u4j7g8a1lI',
    appId: '1:919506372649:ios:d61f07483609af1a6a3438',
    messagingSenderId: '919506372649',
    projectId: 'flungry',
    storageBucket: 'flungry.appspot.com',
    iosClientId: '919506372649-ec57v4g6n822sq37ivb72g5c8slmh61h.apps.googleusercontent.com',
    iosBundleId: 'com.example.flungry',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBqJ7Aan72yxl_iH8xwi6wN4u4j7g8a1lI',
    appId: '1:919506372649:ios:d61f07483609af1a6a3438',
    messagingSenderId: '919506372649',
    projectId: 'flungry',
    storageBucket: 'flungry.appspot.com',
    iosClientId: '919506372649-ec57v4g6n822sq37ivb72g5c8slmh61h.apps.googleusercontent.com',
    iosBundleId: 'com.example.flungry',
  );
}
